#!/bin/bash
for i in *."$1"; do ffmpeg -i "$i" -vf hflip "${i%.*}_flipped."$1""
if [ -z "$1" ]; then
echo "Enter valid image extention";
break;
else
mkdir output;
mv --verbose *flipped* ./output/
fi
done
